# Generated by Django 5.0.3 on 2024-03-24 05:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0002_song_arist"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Arist",
            new_name="Artist",
        ),
    ]
