# Generated by Django 5.0.3 on 2024-03-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0003_rename_arist_artist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="playlist",
        ),
        migrations.AddField(
            model_name="song",
            name="playlists",
            field=models.ManyToManyField(to="playlists.playlist"),
        ),
    ]
